apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-capstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-capstone
  template:
    metadata:
      labels:
        app: devops-capstone
    spec:
      containers:
      - name: devops-capstone
        image: 019876704237.dkr.ecr.us-east-2.amazonaws.com/devops-capstone-project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: default-port