apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-capstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-capstone
  template:
    metadata:
      labels:
        app: devops-capstone
    spec:
      containers:
      - name: devops-capstone
        image: rafaekhatri11/udacity-capstone-project-final:master
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: default-port