apiVersion: v1
kind: Service
metadata:
  name: devops-capstone
  labels:
    app: devops-capstone
spec:
  type: LoadBalancer
  selector:
    app: devops-capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80